### ISSUE TITLE
cloned dapp bug

### ISSUE THREAD

**Issue by dtribble** [Agoric/cross-chain-hackathon#7]
Platform: WSL Ubuntu (Windows on Linux)
"before Using Agoric" and "Starting a Project" followed.

**Comment by Kmccabe** [comment]
```
goric: install: Done installing
kmccabe@DESKTOP-KAA66K9:/mnt/c/Users/Desktop/goodwill/gw$ agoric start --reset
agoric: start: removing _agstate/agoric-servers/dev
agoric: start: initializing dev
fatal: bad revision 'HEAD'
agoric: start: setting sim chain with 0 second delay
SwingSet: vat-http: sendBroadcast -1 -1 -1
launch-chain: Launching SwingSet kernel
web: Listening on 127.0.0.1:8000
start: swingset running
SwingSet: vat-wallet: Adding adminHandle Object <[Object: null prototype] {}> {
  dispatcher: 'onOpen',
  origin: 'http://localhost:8000',
  url: '/private/wallet',
  date: 1588529429248,
  channelHandle: Presence o-66 <[Object: null prototype] [Presence o-66] {}> [Presence o-66] {}
}
SwingSet: vat-wallet: Have error ReferenceError: idToCancel is not defined
    at Object.acceptOffer (/SwingSet/vat-wallet/goodwill/gw/_agstate/agoric-servers/dev/vats/lib-wallet.js:335:9)
    at async Object.adminOnMessage [as onMessage] (/SwingSet/vat-wallet/goodwill/gw/_agstate/agoric-servers/dev/vats/vat-wallet.js:143:17)
web: 127.0.0.1:56230[4]: inbound error: idToCancel is not defined from {
  "type": "walletAcceptOffer",
  "data": "http://localhost:8000#1588529423303",
  "meta": {
    "channelID": 4,
    "origin": "http://localhost:8000",
    "url": "/private/wallet",
    "date": 1588529439840
  }
}
web: 127.0.0.1:56230[4]: inbound error: target[onError] does not exist, has onOpen,onClose,onMessage from {
  "type": "walletAcceptOffer",
  "data": "http://localhost:8000#1588529423303",
  "error": "\"idToCancel is not defined\"",
  "meta": {
    "channelID": 4,
    "dispatcher": "onError",
    "origin": "http://localhost:8000",
    "url": "/private/wallet",
    "date": 1588529440142
  }
}
```

**Comment by dtribble** [comment]
`idToCancel` only appears in `lib-wallet.js`, and "cancel" was renamed to "complete", so I speculate that it should have been another usage of `idToComplete`. Kevin is trying that.
